### ISSUE TITLE
Using InstaStories on batch mode (crontab)

### ISSUE THREAD

**Issue by VanilleAngeles** [powahftw/InstaStories#24]
Hello,
It's not a really issue.
Previously, I was using Instastories to download stories from selected accounts. The program was using "instagram_private_api".
A daily job (crontab) was scheduled.
Since 1st of april, the format seem to change because, on jpg file I have this message when I want to visualize pictures: "(Not a JPEG file: starts with 0x52 0x49)".
For me, the web access of this program is fine but I can't use it in batch mode.
I have read documentation whitout find a solution of my problem.
My question: is there a method to submit Instastories in batch mode for automatisation ?
Thans for your answer.

**Comment by VanilleAngeles** [comment]
Good evening,
For the format, I have a answer. I Think the new format for upload pictures is webp insteed jpg since the 1st of april. I have changed in the original program, it's fine.
So my request is only for "batch mode" ... 
Thanks

**Comment by powahftw** [comment]
Hey Vanille, just saw this. Glad to see you find a way around the image format. Could you clarify what's are you requesting for "batch mode"? 

We used to have something similar in the past (see https://github.com/mvkv/InstaStories/blob/e973d5c6e00fe7e09229287e3da08813a00ebfaf/runner.py) but we decided to only focus on the GUI.
