### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by naziko2411** [powahftw/InstaStories#5]
Hey there! I am focusing to Instagram Stories Database since January 2020. It looks like isdb.pw not supporting all users. Help me how to use this script so the program won't close itself? My computer script programs close after downloading. Can you help me for it, please?

**Comment by powahftw** [comment]
You can look at the readme/code to figure out how to use it. Where are you getting stuck specifically?

**Comment by naziko2411** [comment]
I've just installed Python 3.8 but it didn't work. I've also installed Visual Studio 2019 for Instastories.py. Should I use Visual Studio 2019?

**Comment by powahftw** [comment]
What you mean it didn't work? Can you post the error you get? Using this from any IDE / command line should work, provided you filled in your data in the script.

**Comment by naziko2411** [comment]
Well, I tried to retrieve files from a media date, but it had specific errors when I'm using Visual Studio Code. I'm trying to retrieve photos and videos without getting errors.

**Comment by naziko2411** [comment]
Also, I used a user id and nicknames, it also recieved errors. That's why I'm stuck. Show me the steps for using Instastories.py, please.

**Comment by powahftw** [comment]
The is a big ########### INSERT HERE ############# part in the code to provide your cookie, did you do that?
Also the extra_id variable you either make it empty [] or fill it with your values. 

Can you past the stack trace of the errors you get?

**Comment by naziko2411** [comment]
Ah, I see. Providing cookies will work to retrieve files.
